### ISSUE TITLE
Sincerely look forward to further communication.

### ISSUE THREAD

**Issue by zcode86** [JappaB/Active_Learning_Object_Detection#2]
Hello, I am very interested in your work. Can I have your WeChat or QQ to have  a further talk?  This is my mail (2071413919@qq.com), you can provide it through this mail, thanks.

**Comment by JappaB** [comment]
Hi there @zcode86 ,
My apologies for the extremely late reply. I've been focussed on other things for quite some time.
I don't have wechat nor QQ, but you can ask questions through here. Perhaps others can learn as well ;)
